name: Build Docs
on:
  repository_dispatch:
    types:
      - plugins-updated
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 9
      - run: |
          sudo apt install jq curl -y
          rm vitepress/plugins.json
          wget https://raw.githubusercontent.com/pot-app/pot-app-plugin-list/main/list.json -O vitepress/plugins.json
          ver=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/allentown521/saladict/releases/latest | jq '.tag_name'|tr -d 'v"')
          sed -i "s/const version =.*/const version = '${ver}'/" vitepress/download.md
          sed -i "s/const version =.*/const version = '${ver}'/" vitepress/en/download.md
      - run: pnpm i && pnpm docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vitepress/.vitepress/dist
